# -*- coding: utf-8 -*-
"""one_hot_encoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H2alJeH7Ar35YmdAJ57MSzJPDgXtFA48
"""

!pip install kaggle

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle

!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d yogeerp/mercedes

from zipfile import ZipFile
filename="/content/mercedes.zip"

with ZipFile(filename, "r") as zip:
  zip.extractall()
  print("Done")

import pandas as pd
import numpy as np

data = pd.read_csv("/content/mercedesbenz.csv", usecols=["X1","X2","X3", "X4", "X5", "X6"])
data.head()

for cols in data.columns:
  print(cols, ":", len(data[cols].unique()), "labels")

data.X2.value_counts().sort_values(ascending=False).head(20)

top_10 = [x for x in data.X2.value_counts().sort_values(ascending=False).head(10).index]
top_10

for label in top_10:
  data[label] = np.where(data["X2"]==label, 1, 0)
data[['X2']+top_10].head()

def one_hot_encoding(data, variable, top_x_labels):
  for label in top_x_labels:
    data[variable,"_",label] = np.where(data[variable]==label, 1, 0)

df = pd.read_csv("/content/mercedesbenz.csv", usecols=["X1","X2","X3", "X4", "X5", "X6"])
df.head()

one_hot_encoding(df, "X3", top_10)
df.head()

